services:
  db:
    image: postgres:16
    container_name: desafio-pb-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-moviedb}
      POSTGRES_USER: ${POSTGRES_USER:-movieuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-moviepass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: desafio-pb-backend
    env_file:
      - .env
    environment:
      FLASK_APP: "app:create_app"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "8000"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://${POSTGRES_USER:-movieuser}:${POSTGRES_PASSWORD:-moviepass}@db:5432/${POSTGRES_DB:-moviedb}"
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    command: >
      bash -lc "flask db upgrade &&
                flask commands seed &&
                flask run"
                

  frontend:
    build:
      context: ./frontend
    container_name: desafio-pb-frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"
    # se teu front usa env em build/runtime, dÃ¡ pra passar aqui
    # environment:
    #   VITE_API_URL: "http://localhost:8000"
    command: >
      sh -lc "pnpm build && pnpm preview --host 0.0.0.0 --port 8080"

volumes:
  pgdata:
